apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: mm-multilang
          artifact-id: 35f9843c-610b-4263-ab14-abfd8b015804
          # artifact-id: 3caddc9e-d7cc-42c9-a8c1-95c025dcd211 #demo-go-service
          target-environment: QA
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: 35f9843c-610b-4263-ab14-abfd8b015804 
          target-environment: testQAEnv
