apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: demo-go-service
          artifact-id: 7c12fbd2-61d0-45f5-a21a-db28461fbb3e #demo-go-service
          # artifact-id: 3caddc9e-d7cc-42c9-a8c1-95c025dcd211 #demo-go-service
          target-environment: preprod-us-east-1
      # - uses: cloudbees-io/register-deployed-artifact@v2
      #   with:
      #     labels: demo-go-service
      #     artifact-id: 7c12fbd2-61d0-45f5-a21a-db28461fbb3e #demo-go-service
      #     target-environment: Prasen-App-PreProd-Test-Env
